spring:
  application:
    name: card
  datasource:
    url: jdbc:postgresql://localhost:5432/click-card?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    servlet:
      path: /graphql
    tools:
      schema-location-pattern: classpath:graphql/**/*.graphqls
    graphiql:
      endpoint: /graphiql
      enabled: true

jwt:
  secret: thisispublickeythisispublickeythisispublickeythisispublickey
  expiration: 86400000