spring:
  application:
    name: card
  datasource:
    url: jdbc:postgresql://localhost:5432/click?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:gcs.json
        project-id: vibrant-depth-424101-m7
        bucket: cardimg_bucket
    aws:
      s3:
        bucket: click-card
      credentials:
        accessKey:
        secretKey:
      region:
        static: ap-northeast-2
      stack:
        auto: false


  graphql:
    servlet:
      path: /graphql
    tools:
      schema-location-pattern: classpath:graphql/**/*.graphqls
    graphiql:
      endpoint: /graphiql
      enabled: true


jwt:
  secret: thisispublickeythisispublickeythisispublickeythisispublickey
hash:
  iterations: 128

#  expiration: 86400000





