spring:
  application:
    name: card
  datasource:
    url: jdbc:postgresql://card-postgres-card:5432/click_card?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: {user}
    password: {password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gcp:
      storage:
        credentials:
#          location: classpath:gcs.json
#          location: {storage}
#           location: file:\card\src\main\resources\gcs.json
           location: file:/home/sylim0513/.ssh/storage_key
        project-id: vibrant-depth-424101-m7
        bucket: cardimg_bucket

  graphql:
    servlet:
      path: /graphql
    tools:
      schema-location-pattern: classpath:graphql/**/*.graphqls
    graphiql:
      endpoint: /graphql
      enabled: true

jwt:
  secret: {secret}
hash:
    iterations: 128

