spring:
  application:
    name: card
  datasource:
    url: jdbc:postgresql://localhost:5432/click?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:springboot-storage-key.json
        project-id: vibrant-depth-424101-m7
        bucket: cardimg_bucket

#          location: classpath:springboot-storage-key.json
#        project-id: vibrant-depth-424101-m7
#        bucket:  cardimg_bucket

jwt:
  secret: thisispublickeythisispublickeythisispublickeythisispublickey

#  expiration: 86400000





